# Generated by Django 5.1.1 on 2024-09-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdk_cz', '0002_alter_project_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list',
            new_name='flist',
        ),
        migrations.RenameField(
            model_name='list_item',
            old_name='list',
            new_name='flist',
        ),
    ]
