# Generated by Django 5.1.1 on 2024-09-12 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdk_cz', '0004_alter_activity_log_user_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_item',
            name='created',
            field=models.DateTimeField(db_column='created', default=django.utils.timezone.now),
        ),
    ]
