# Generated by Django 5.1.1 on 2024-09-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdk_cz', '0006_alter_list_item_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flist',
            name='modified',
            field=models.DateTimeField(blank=True, db_column='modified', null=True),
        ),
    ]
