# Generated by Django 5.1.1 on 2024-09-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdk_cz', '0008_item_warehouse_contact_contract_transaction_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contract',
            table='FDK_contract',
        ),
        migrations.AlterModelTable(
            name='item',
            table='FDK_warwarehouse_item',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='FDK_warwarehouse_transaction',
        ),
        migrations.AlterModelTable(
            name='warehouse',
            table='FDK_warwarehouse',
        ),
    ]
