# Generated by Django 5.1.1 on 2024-09-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdk_cz', '0009_alter_contract_table_alter_item_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='FDK_warehouse_item',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='FDK_warehouse_transaction',
        ),
        migrations.AlterModelTable(
            name='warehouse',
            table='FDK_warehouse',
        ),
    ]
