# Generated by Django 5.1.1 on 2024-09-13 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdk_cz', '0010_alter_item_table_alter_transaction_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='permission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'FDK_permissions',
            },
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'FDK_roles',
            },
        ),
        migrations.CreateModel(
            name='list_permission',
            fields=[
                ('list_permission_id', models.AutoField(db_column='list_permission_id', primary_key=True, serialize=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('flist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='fdk_cz.flist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FDK_list_permissions',
            },
        ),
        migrations.CreateModel(
            name='project_user',
            fields=[
                ('project_user_id', models.AutoField(db_column='project_user_id', primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='fdk_cz.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_project', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='fdk_cz.role')),
            ],
            options={
                'db_table': 'FDK_project_user',
            },
        ),
        migrations.CreateModel(
            name='role_permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fdk_cz.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='fdk_cz.role')),
            ],
            options={
                'db_table': 'FDK_role_permisssions',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
