# Generated by Django - state sync migration
# This migration adds models to Django's state that already exist in the database

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Sync Django's migration state with the actual database schema.
    These models/fields already exist in the database but weren't properly tracked in migrations.
    Using SeparateDatabaseAndState to avoid trying to create them again.
    """

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fdk_cz', '0013_add_soft_delete'),
    ]

    operations = [
        # WarehouseCategory model
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='WarehouseCategory',
                    fields=[
                        ('category_id', models.AutoField(db_column='category_id', primary_key=True, serialize=False)),
                        ('name', models.CharField(db_column='name', max_length=255)),
                        ('description', models.TextField(blank=True, db_column='description', null=True)),
                    ],
                    options={
                        'db_table': 'FDK_warehouse_category',
                        'verbose_name_plural': 'Warehouse Categories',
                    },
                ),
            ],
            database_operations=[],
        ),

        # Add category to WarehouseItem
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='warehouseitem',
                    name='category',
                    field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='fdk_cz.warehousecategory'),
                ),
            ],
            database_operations=[],
        ),

        # Add organization to Warehouse
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='warehouse',
                    name='organization',
                    field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='fdk_cz.organization'),
                ),
            ],
            database_operations=[],
        ),

        # Add project to Warehouse
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='warehouse',
                    name='project',
                    field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='fdk_cz.project'),
                ),
            ],
            database_operations=[],
        ),

        # Add grant_number to GrantCall
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='grantcall',
                    name='grant_number',
                    field=models.CharField(blank=True, db_column='grant_number', help_text='Oficiální číslo dotace (např. 1508)', max_length=100, null=True),
                ),
            ],
            database_operations=[],
        ),

        # Add grant_subnumber to GrantCall
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='grantcall',
                    name='grant_subnumber',
                    field=models.CharField(blank=True, db_column='grant_subnumber', help_text='Podčíslo dotace (pokud existuje)', max_length=100, null=True),
                ),
            ],
            database_operations=[],
        ),

        # TestScenario model
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='TestScenario',
                    fields=[
                        ('scenario_id', models.AutoField(db_column='scenario_id', primary_key=True, serialize=False)),
                        ('name', models.CharField(db_column='name', max_length=255)),
                        ('description', models.TextField(blank=True, db_column='description', null=True)),
                        ('steps', models.TextField(db_column='steps', help_text='Kroky testovacího scénáře')),
                        ('expected_result', models.TextField(blank=True, db_column='expected_result', null=True)),
                        ('priority', models.CharField(choices=[('low', 'Nízká'), ('medium', 'Střední'), ('high', 'Vysoká'), ('critical', 'Kritická')], db_column='priority', default='medium', max_length=20)),
                        ('status', models.CharField(choices=[('draft', 'Koncept'), ('active', 'Aktivní'), ('deprecated', 'Zastaralý')], db_column='status', default='active', max_length=20)),
                        ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                        ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                        ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_scenarios', to=settings.AUTH_USER_MODEL)),
                        ('organization', models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_scenarios', to='fdk_cz.organization')),
                        ('owner', models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_test_scenarios', to=settings.AUTH_USER_MODEL)),
                        ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_scenarios', to='fdk_cz.project')),
                    ],
                    options={
                        'db_table': 'FDK_test_scenario',
                        'ordering': ['-created_at'],
                    },
                ),
            ],
            database_operations=[],
        ),

        # AccountingContext model
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='AccountingContext',
                    fields=[
                        ('context_id', models.AutoField(db_column='context_id', primary_key=True, serialize=False)),
                        ('accounting_type', models.CharField(choices=[('personal', 'Osobní (OSVČ)'), ('organizational', 'Organizační')], db_column='accounting_type', help_text='Typ účetnictví', max_length=20)),
                        ('accounting_method', models.CharField(choices=[('simple', 'Jednoduché účetnictví'), ('double_entry', 'Podvojné účetnictví')], db_column='accounting_method', default='double_entry', max_length=20)),
                        ('fiscal_year', models.IntegerField(db_column='fiscal_year', help_text='Fiskální rok (např. 2025)')),
                        ('name', models.CharField(db_column='name', help_text='Název účetní knihy', max_length=255)),
                        ('is_active', models.BooleanField(db_column='is_active', default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                        ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                        ('organization', models.ForeignKey(blank=True, db_column='organization_id', help_text='Organizace (pokud je organizační)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_contexts', to='fdk_cz.organization')),
                        ('user', models.ForeignKey(db_column='user_id', help_text='Vlastník účetnictví', on_delete=django.db.models.deletion.CASCADE, related_name='accounting_contexts', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'FDK_accounting_context',
                        'ordering': ['-fiscal_year', 'name'],
                        'unique_together': {('user', 'organization', 'fiscal_year', 'name')},
                    },
                ),
            ],
            database_operations=[],
        ),

        # AccountingAccount model
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='AccountingAccount',
                    fields=[
                        ('account_id', models.AutoField(db_column='account_id', primary_key=True, serialize=False)),
                        ('account_number', models.CharField(db_column='account_number', help_text='Číslo účtu (221, 321, 518...)', max_length=20)),
                        ('name', models.CharField(db_column='name', help_text='Název účtu', max_length=255)),
                        ('account_type', models.CharField(choices=[('asset', 'Aktiva'), ('liability', 'Pasiva'), ('equity', 'Vlastní kapitál'), ('revenue', 'Výnosy'), ('expense', 'Náklady')], db_column='account_type', max_length=20)),
                        ('description', models.TextField(blank=True, db_column='description', null=True)),
                        ('is_active', models.BooleanField(db_column='is_active', default=True)),
                        ('context', models.ForeignKey(db_column='context_id', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='fdk_cz.accountingcontext')),
                    ],
                    options={
                        'db_table': 'FDK_accounting_account',
                        'ordering': ['account_number'],
                    },
                ),
                migrations.AddIndex(
                    model_name='accountingaccount',
                    index=models.Index(fields=['context', 'account_type'], name='FDK_account_context_4e86e1_idx'),
                ),
                migrations.AddIndex(
                    model_name='accountingaccount',
                    index=models.Index(fields=['account_number'], name='FDK_account_account_8ddbe2_idx'),
                ),
                migrations.AlterUniqueTogether(
                    name='accountingaccount',
                    unique_together={('context', 'account_number')},
                ),
            ],
            database_operations=[],
        ),

        # JournalEntry model
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='JournalEntry',
                    fields=[
                        ('entry_id', models.AutoField(db_column='entry_id', primary_key=True, serialize=False)),
                        ('entry_number', models.CharField(db_column='entry_number', help_text='Číslo účetního zápisu', max_length=50)),
                        ('entry_date', models.DateField(db_column='entry_date', help_text='Datum účetního případu')),
                        ('description', models.TextField(db_column='description', help_text='Popis účetního případu')),
                        ('document_number', models.CharField(blank=True, db_column='document_number', help_text='Číslo dokladu (faktury, pokladního dokladu...)', max_length=100, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                        ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                        ('is_posted', models.BooleanField(db_column='is_posted', default=True, help_text='Je zaúčtováno?')),
                        ('context', models.ForeignKey(db_column='context_id', on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='fdk_cz.accountingcontext')),
                        ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL)),
                        ('invoice', models.ForeignKey(blank=True, db_column='invoice_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='fdk_cz.invoice')),
                    ],
                    options={
                        'db_table': 'FDK_journal_entry',
                        'ordering': ['-entry_date', '-entry_number'],
                    },
                ),
                migrations.AddIndex(
                    model_name='journalentry',
                    index=models.Index(fields=['context', 'entry_date'], name='FDK_journal_context_c66a51_idx'),
                ),
                migrations.AddIndex(
                    model_name='journalentry',
                    index=models.Index(fields=['entry_number'], name='FDK_journal_entry_n_ea5ce8_idx'),
                ),
            ],
            database_operations=[],
        ),

        # JournalEntryLine model
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='JournalEntryLine',
                    fields=[
                        ('line_id', models.AutoField(db_column='line_id', primary_key=True, serialize=False)),
                        ('debit_amount', models.DecimalField(db_column='debit_amount', decimal_places=2, default=0, help_text='Má dáti (MD)', max_digits=15)),
                        ('credit_amount', models.DecimalField(db_column='credit_amount', decimal_places=2, default=0, help_text='Dal (D)', max_digits=15)),
                        ('description', models.CharField(blank=True, db_column='description', max_length=500, null=True)),
                        ('line_order', models.IntegerField(db_column='line_order', default=0)),
                        ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='journal_lines', to='fdk_cz.accountingaccount')),
                        ('journal_entry', models.ForeignKey(db_column='entry_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='fdk_cz.journalentry')),
                    ],
                    options={
                        'db_table': 'FDK_journal_entry_line',
                        'ordering': ['journal_entry', 'line_order'],
                    },
                ),
                migrations.AddIndex(
                    model_name='journalentryline',
                    index=models.Index(fields=['journal_entry', 'account'], name='FDK_journal_entry_i_b77d2d_idx'),
                ),
            ],
            database_operations=[],
        ),

        # BalanceSheet model
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='BalanceSheet',
                    fields=[
                        ('balance_id', models.AutoField(db_column='balance_id', primary_key=True, serialize=False)),
                        ('balance_type', models.CharField(choices=[('opening', 'Počáteční'), ('closing', 'Konečná')], db_column='balance_type', max_length=20)),
                        ('fiscal_year', models.IntegerField(db_column='fiscal_year')),
                        ('debit_balance', models.DecimalField(db_column='debit_balance', decimal_places=2, default=0, help_text='Zůstatek MD', max_digits=15)),
                        ('credit_balance', models.DecimalField(db_column='credit_balance', decimal_places=2, default=0, help_text='Zůstatek D', max_digits=15)),
                        ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                        ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                        ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='balance_entries', to='fdk_cz.accountingaccount')),
                        ('context', models.ForeignKey(db_column='context_id', on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheets', to='fdk_cz.accountingcontext')),
                    ],
                    options={
                        'db_table': 'FDK_balance_sheet',
                        'ordering': ['fiscal_year', 'account__account_number'],
                        'unique_together': {('context', 'account', 'balance_type', 'fiscal_year')},
                    },
                ),
                migrations.AddIndex(
                    model_name='balancesheet',
                    index=models.Index(fields=['context', 'fiscal_year', 'balance_type'], name='FDK_balance_context_722aee_idx'),
                ),
            ],
            database_operations=[],
        ),

        # UserModulePreference model
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='UserModulePreference',
                    fields=[
                        ('preference_id', models.AutoField(db_column='preference_id', primary_key=True, serialize=False)),
                        ('is_visible', models.BooleanField(db_column='is_visible', default=True)),
                        ('display_order', models.IntegerField(db_column='display_order', default=0)),
                        ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                        ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                        ('module', models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='fdk_cz.module')),
                        ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='module_preferences', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'FDK_user_module_preference',
                        'ordering': ['display_order', 'module__order'],
                        'unique_together': {('user', 'module')},
                    },
                ),
            ],
            database_operations=[],
        ),

        # HelpArticle model
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='HelpArticle',
                    fields=[
                        ('article_id', models.AutoField(db_column='article_id', primary_key=True, serialize=False)),
                        ('title', models.CharField(db_column='title', max_length=255)),
                        ('slug', models.SlugField(db_column='slug', max_length=255, unique=True)),
                        ('content', models.TextField(db_column='content', help_text='Markdown formátovaný text')),
                        ('category', models.CharField(choices=[('intro', 'Obecný úvod'), ('module', 'Dokumentace modulu'), ('technical', 'Technická dokumentace'), ('faq', 'Často kladené otázky')], db_column='category', max_length=20)),
                        ('order', models.IntegerField(db_column='order', default=0, help_text='Pořadí zobrazení (nižší = dříve)')),
                        ('is_published', models.BooleanField(db_column='is_published', default=True)),
                        ('is_technical', models.BooleanField(db_column='is_technical', default=False, help_text='Viditelné pouze pro administrátory a testery')),
                        ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                        ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                        ('meta_description', models.CharField(blank=True, db_column='meta_description', max_length=255, null=True)),
                        ('keywords', models.CharField(blank=True, db_column='keywords', help_text='Klíčová slova oddělená čárkami', max_length=500, null=True)),
                        ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_help_articles', to=settings.AUTH_USER_MODEL)),
                        ('module', models.ForeignKey(blank=True, db_column='module_id', help_text='Modul, ke kterému se článek vztahuje', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_articles', to='fdk_cz.module')),
                    ],
                    options={
                        'db_table': 'FDK_help_article',
                        'ordering': ['order', 'title'],
                    },
                ),
                migrations.AddIndex(
                    model_name='helparticle',
                    index=models.Index(fields=['category', 'is_published'], name='FDK_help_ar_categor_9ea006_idx'),
                ),
                migrations.AddIndex(
                    model_name='helparticle',
                    index=models.Index(fields=['module', 'is_published'], name='FDK_help_ar_module__b9db2f_idx'),
                ),
            ],
            database_operations=[],
        ),

        # SwotAnalysis model
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='SwotAnalysis',
                    fields=[
                        ('swot_id', models.AutoField(db_column='swot_id', primary_key=True, serialize=False)),
                        ('title', models.CharField(db_column='title', max_length=255)),
                        ('description', models.TextField(blank=True, db_column='description', null=True)),
                        ('strengths', models.JSONField(db_column='strengths', default=list, help_text='Silné stránky - [{"text": "...", "weight": 1-10}, ...]')),
                        ('weaknesses', models.JSONField(db_column='weaknesses', default=list, help_text='Slabé stránky - [{"text": "...", "weight": 1-10}, ...]')),
                        ('opportunities', models.JSONField(db_column='opportunities', default=list, help_text='Příležitosti - [{"text": "...", "weight": 1-10}, ...]')),
                        ('threats', models.JSONField(db_column='threats', default=list, help_text='Hrozby - [{"text": "...", "weight": 1-10}, ...]')),
                        ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                        ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                        ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_swot_analyses', to=settings.AUTH_USER_MODEL)),
                        ('organization', models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swot_analyses', to='fdk_cz.organization')),
                        ('owner', models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_swot_analyses', to=settings.AUTH_USER_MODEL)),
                        ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swot_analyses', to='fdk_cz.project')),
                    ],
                    options={
                        'db_table': 'FDK_swot_analysis',
                        'ordering': ['-created_at'],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
