# Generated by Django 5.1.1 on 2024-09-15 20:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdk_cz', '0014_test_test_result_test_error_test_type_test_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_error',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_column='date_created', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_error',
            name='project',
            field=models.ForeignKey(db_column='project_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_errors', to='fdk_cz.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_error',
            name='status',
            field=models.CharField(db_column='status', default='open', max_length=50),
        ),
    ]
