# Generated by Django 5.1.1 on 2025-11-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdk_cz', '0014_warehousecategory_grantcall_grant_number_and_more'),
        ('fdk_cz', '0015_fix_missing_columns'),
    ]

    operations = [
    ]
