# Generated by Django 5.1.1 on 2024-09-22 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdk_cz', '0018_alter_test_error_test_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='fdk_cz.task'),
        ),
        migrations.AlterField(
            model_name='test_error',
            name='status',
            field=models.CharField(choices=[('open', 'Otevřená'), ('closed', 'Uzavřená'), ('in_progress', 'V procesu')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='test_error',
            name='test_result',
            field=models.ForeignKey(db_column='test_result_id', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='fdk_cz.test_result'),
            preserve_default=False,
        ),
    ]
