# Generated by Django 5.1.1 on 2024-10-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdk_cz', '0020_company_invoice_invoice_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_item',
            name='vat_rate',
            field=models.DecimalField(db_column='vat_rate', decimal_places=2, default=21, max_digits=5),
        ),
    ]
