# Generated by Django 5.1.1 on 2024-10-27 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdk_cz', '0021_invoice_item_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fdk_cz.category'),
        ),
    ]
