# Generated by Django 5.1.1 on 2025-07-04 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdk_cz', '0024_warehouse_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='users',
        ),
        migrations.CreateModel(
            name='grant',
            fields=[
                ('grant_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('published_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fdk_cz.category')),
            ],
            options={
                'db_table': 'FDK_grants',
            },
        ),
        migrations.CreateModel(
            name='grant_application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('requested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('granted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('draft', 'Koncept'), ('submitted', 'Odesláno'), ('approved', 'Schváleno'), ('rejected', 'Zamítnuto'), ('in_progress', 'V procesu')], default='draft', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_applications', to=settings.AUTH_USER_MODEL)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='fdk_cz.grant')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_applications', to='fdk_cz.company')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_applications', to='fdk_cz.project')),
            ],
            options={
                'db_table': 'FDK_grant_applications',
            },
        ),
    ]
