# Generated by Django 5.1.1 on 2025-07-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdk_cz', '0025_remove_warehouse_users_grant_grant_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='type',
            field=models.CharField(choices=[('dotace', 'Dotace'), ('grant', 'Grant'), ('stipendium', 'Stipendium')], default='dotace', max_length=50),
        ),
    ]
