# Generated by Django 5.1.1 on 2025-10-18 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdk_cz', '0026_grant_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantCall',
            fields=[
                ('call_id', models.AutoField(db_column='call_id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('provider', models.CharField(blank=True, db_column='provider', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('type', models.CharField(choices=[('dotace', 'Dotace'), ('grant', 'Grant'), ('stipendium', 'Stipendium')], db_column='type', default='dotace', max_length=50)),
                ('start_date', models.DateField(blank=True, db_column='start_date', null=True)),
                ('end_date', models.DateField(blank=True, db_column='end_date', null=True)),
                ('budget', models.DecimalField(blank=True, db_column='budget', decimal_places=2, max_digits=15, null=True)),
                ('eligibility', models.TextField(blank=True, db_column='eligibility', null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('open', 'Open'), ('closed', 'Closed')], db_column='status', default='open', max_length=20)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('published_at', models.DateField(auto_now_add=True, db_column='published_at')),
            ],
            options={
                'db_table': 'FDK_grant_call',
            },
        ),
        migrations.CreateModel(
            name='GrantProgram',
            fields=[
                ('program_id', models.AutoField(db_column='program_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('provider', models.CharField(blank=True, db_column='provider', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('total_budget', models.DecimalField(blank=True, db_column='total_budget', decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
            ],
            options={
                'db_table': 'FDK_grant_program',
            },
        ),
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('number', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='activity_log',
            new_name='ActivityLog',
        ),
        migrations.RenameModel(
            old_name='invoice_item',
            new_name='InvoiceItem',
        ),
        migrations.RenameModel(
            old_name='list_item',
            new_name='ListItem',
        ),
        migrations.RenameModel(
            old_name='list_permission',
            new_name='ListPermission',
        ),
        migrations.RenameModel(
            old_name='attachment',
            new_name='ProjectAttachment',
        ),
        migrations.RenameModel(
            old_name='category',
            new_name='ProjectCategory',
        ),
        migrations.RenameModel(
            old_name='comment',
            new_name='ProjectComment',
        ),
        migrations.RenameModel(
            old_name='document',
            new_name='ProjectDocument',
        ),
        migrations.RenameModel(
            old_name='milestone',
            new_name='ProjectMilestone',
        ),
        migrations.RenameModel(
            old_name='role',
            new_name='ProjectPermission',
        ),
        migrations.RenameModel(
            old_name='permission',
            new_name='ProjectRole',
        ),
        migrations.RenameModel(
            old_name='role_permission',
            new_name='ProjectRolePermission',
        ),
        migrations.RenameModel(
            old_name='task',
            new_name='ProjectTask',
        ),
        migrations.RenameModel(
            old_name='project_user',
            new_name='ProjectUser',
        ),
        migrations.RenameModel(
            old_name='test_error',
            new_name='TestError',
        ),
        migrations.RenameModel(
            old_name='test_result',
            new_name='TestResult',
        ),
        migrations.RenameModel(
            old_name='test_type',
            new_name='TestType',
        ),
        migrations.RenameModel(
            old_name='user',
            new_name='Users2',
        ),
        migrations.RenameModel(
            old_name='item',
            new_name='WarehouseItem',
        ),
        migrations.RenameModel(
            old_name='transaction',
            new_name='WarehouseTransaction',
        ),
        migrations.RemoveField(
            model_name='grant_application',
            name='grant',
        ),
        migrations.RemoveField(
            model_name='grant_application',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='grant_application',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='grant_application',
            name='project',
        ),
        migrations.RenameField(
            model_name='projectpermission',
            old_name='role_id',
            new_name='permission_id',
        ),
        migrations.RenameField(
            model_name='projectpermission',
            old_name='role_name',
            new_name='permission_name',
        ),
        migrations.RenameField(
            model_name='projectrole',
            old_name='permission_id',
            new_name='role_id',
        ),
        migrations.RenameField(
            model_name='projectrole',
            old_name='permission_name',
            new_name='role_name',
        ),
        migrations.AlterField(
            model_name='projectattachment',
            name='uploaded_by',
            field=models.ForeignKey(db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='uploaded_by',
            field=models.ForeignKey(db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='executed_by',
            field=models.ForeignKey(blank=True, db_column='executed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='listpermission',
            unique_together={('flist', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='projectuser',
            unique_together={('project', 'user')},
        ),
        migrations.AlterModelTable(
            name='projectpermission',
            table='FDK_permissions',
        ),
        migrations.AlterModelTable(
            name='projectrole',
            table='FDK_roles',
        ),
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('application_id', models.AutoField(db_column='application_id', primary_key=True, serialize=False)),
                ('submission_date', models.DateField(blank=True, db_column='submission_date', null=True)),
                ('approval_date', models.DateField(blank=True, db_column='approval_date', null=True)),
                ('requested_amount', models.DecimalField(blank=True, db_column='requested_amount', decimal_places=2, max_digits=12, null=True)),
                ('granted_amount', models.DecimalField(blank=True, db_column='granted_amount', decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('draft', 'Koncept'), ('submitted', 'Odesláno'), ('approved', 'Schváleno'), ('rejected', 'Zamítnuto'), ('in_progress', 'V procesu')], db_column='status', default='draft', max_length=50)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('is_successful', models.BooleanField(db_column='is_successful', default=False)),
                ('is_visible', models.BooleanField(db_column='is_visible', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('applicant', models.ForeignKey(blank=True, db_column='applicant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_applications', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_applications', to='fdk_cz.company')),
                ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_applications', to='fdk_cz.project')),
                ('call', models.ForeignKey(db_column='call_id', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='fdk_cz.grantcall')),
            ],
            options={
                'db_table': 'FDK_grant_application',
            },
        ),
        migrations.AddField(
            model_name='grantcall',
            name='program',
            field=models.ForeignKey(blank=True, db_column='program_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='fdk_cz.grantprogram'),
        ),
        migrations.CreateModel(
            name='GrantRequirement',
            fields=[
                ('requirement_id', models.AutoField(db_column='requirement_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('is_mandatory', models.BooleanField(db_column='is_mandatory', default=True)),
                ('call', models.ForeignKey(db_column='call_id', on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='fdk_cz.grantcall')),
            ],
            options={
                'db_table': 'FDK_grant_requirement',
            },
        ),
        migrations.CreateModel(
            name='GrantApplicationDocument',
            fields=[
                ('document_id', models.AutoField(db_column='document_id', primary_key=True, serialize=False)),
                ('file', models.FileField(db_column='file', upload_to='grant_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_column='uploaded_at')),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fdk_cz.grantapplication')),
                ('requirement', models.ForeignKey(blank=True, db_column='requirement_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_documents', to='fdk_cz.grantrequirement')),
            ],
            options={
                'db_table': 'FDK_grant_application_document',
            },
        ),
        migrations.CreateModel(
            name='LawDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('contract', 'Smlouva'), ('agreement', 'Dohoda'), ('template', 'Šablona'), ('analysis', 'Analýza'), ('opinion', 'Stanovisko')], max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LawQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('question', models.TextField()),
                ('ai_response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Čeká na zpracování'), ('processing', 'Zpracovává se'), ('completed', 'Dokončeno'), ('failed', 'Chyba')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ico', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Člen'), ('viewer', 'Pozorovatel')], max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fdk_cz.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(through='fdk_cz.OrganizationMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='grant',
        ),
        migrations.DeleteModel(
            name='grant_application',
        ),
    ]
