# Generated by Django 5.1.1 on 2025-10-18 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdk_cz', '0027_grantcall_grantprogram_law_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fdk_cz.projectpermission'),
        ),
        migrations.AlterField(
            model_name='projectrolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='fdk_cz.projectrole'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='fdk_cz.projectrole'),
        ),
    ]
