# Generated by Django 5.1.1 on 2025-10-19 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdk_cz', '0029_recreate_law_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='law_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('number', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lawquery',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lawquery',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='lawquery',
            name='user',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='id',
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='fdk_cz.organization'),
        ),
        migrations.AddField(
            model_name='lawquery',
            name='query_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_id',
            field=models.AutoField(db_column='organization_id', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='law',
            name='category',
            field=models.CharField(db_column='category', max_length=100),
        ),
        migrations.AlterField(
            model_name='law',
            name='content',
            field=models.TextField(db_column='content'),
        ),
        migrations.AlterField(
            model_name='law',
            name='created_at',
            field=models.DateTimeField(db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='law',
            name='effective_date',
            field=models.DateField(db_column='effective_date'),
        ),
        migrations.AlterField(
            model_name='law',
            name='id',
            field=models.BigAutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='law',
            name='number',
            field=models.CharField(db_column='number', max_length=50),
        ),
        migrations.AlterField(
            model_name='law',
            name='title',
            field=models.CharField(db_column='title', max_length=300),
        ),
        migrations.AlterField(
            model_name='law',
            name='year',
            field=models.IntegerField(db_column='year'),
        ),
        migrations.AlterField(
            model_name='lawdocument',
            name='document_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lawquery',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lawquery',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lawquery',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='law',
            table='FDK_law',
        ),
        migrations.AlterModelTable(
            name='lawquery',
            table='FDK_law_query',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='FDK_organization',
        ),
        migrations.CreateModel(
            name='law_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('contract', 'Smlouva'), ('agreement', 'Dohoda'), ('template', 'Šablona'), ('analysis', 'Analýza'), ('opinion', 'Stanovisko')], max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='law_query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('question', models.TextField()),
                ('ai_response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Čeká na zpracování'), ('processing', 'Zpracovává se'), ('completed', 'Dokončeno'), ('failed', 'Chyba')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
