# Generated by Django 5.1.1 on 2025-10-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdk_cz', '0030_law_detail_remove_lawquery_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organizationmembership',
            table='fdk_cz_organizationmembership',
        ),
    ]
