# Generated by Django 5.1.1 on 2025-10-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdk_cz', '0031_alter_organizationmembership_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organizationmembership',
            table='FDK_organization_membership',
        ),
    ]
