# Generated by Django 5.1.1 on 2025-10-25 12:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdk_cz', '0032_alter_organizationmembership_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('slug', models.SlugField(db_column='slug', max_length=255, unique=True)),
                ('category', models.CharField(choices=[('Page', 'Webová stránka'), ('Help', 'Nápověda / Dokumentace'), ('Announcement', 'Oznámení / Novinka'), ('Blog', 'Blogový příspěvek'), ('Internal', 'Interní poznámka')], db_column='category', default='Page', max_length=50)),
                ('content', models.TextField(db_column='content')),
                ('summary', models.TextField(blank=True, db_column='summary', help_text='Krátký perex nebo popis', null=True)),
                ('meta_header', models.TextField(blank=True, db_column='meta_header', help_text='HTML kód do <head> (např. knihovny, meta tagy)')),
                ('meta_footer', models.TextField(blank=True, db_column='meta_footer', help_text='HTML/JS kód před </body>')),
                ('is_published', models.BooleanField(db_column='is_published', default=True)),
                ('is_featured', models.BooleanField(db_column='is_featured', default=False, help_text='Zobrazit v hlavních oznámeních nebo na dashboardu')),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('author', models.ForeignKey(blank=True, db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FDK_articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
