# Generated by Django 5.1.1 on 2025-11-01 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fdk_cz", "0033_article"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "module_id",
                    models.AutoField(
                        db_column="module_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(db_column="name", max_length=100, unique=True),
                ),
                (
                    "display_name",
                    models.CharField(db_column="display_name", max_length=200),
                ),
                (
                    "display_name_en",
                    models.CharField(
                        blank=True,
                        db_column="display_name_en",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("description", models.TextField(db_column="description")),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        db_column="short_description",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        db_column="price_monthly",
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                    ),
                ),
                (
                    "price_yearly",
                    models.DecimalField(
                        db_column="price_yearly",
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                    ),
                ),
                ("is_free", models.BooleanField(db_column="is_free", default=False)),
                ("is_active", models.BooleanField(db_column="is_active", default=True)),
                (
                    "requires_organization",
                    models.BooleanField(
                        db_column="requires_organization", default=False
                    ),
                ),
                (
                    "url_patterns",
                    models.JSONField(db_column="url_patterns", default=list),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, db_column="icon", max_length=50, null=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        db_column="color", default="#3b82f6", max_length=7
                    ),
                ),
                ("order", models.IntegerField(db_column="order", default=0)),
                (
                    "free_limit",
                    models.IntegerField(blank=True, db_column="free_limit", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
            ],
            options={
                "db_table": "FDK_module",
                "ordering": ["order", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="ModuleBundle",
            fields=[
                (
                    "bundle_id",
                    models.AutoField(
                        db_column="bundle_id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=100)),
                (
                    "display_name",
                    models.CharField(db_column="display_name", max_length=200),
                ),
                ("description", models.TextField(db_column="description")),
                (
                    "price_monthly",
                    models.DecimalField(
                        db_column="price_monthly", decimal_places=2, max_digits=10
                    ),
                ),
                (
                    "price_yearly",
                    models.DecimalField(
                        db_column="price_yearly", decimal_places=2, max_digits=10
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        db_column="discount_percentage",
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(db_column="is_active", default=True)),
                (
                    "is_featured",
                    models.BooleanField(db_column="is_featured", default=False),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, db_column="icon", max_length=50, null=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        db_column="color", default="#3b82f6", max_length=7
                    ),
                ),
                ("order", models.IntegerField(db_column="order", default=0)),
                (
                    "modules",
                    models.ManyToManyField(related_name="bundles", to="fdk_cz.module"),
                ),
            ],
            options={
                "db_table": "FDK_module_bundle",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UserModuleSubscription",
            fields=[
                (
                    "subscription_id",
                    models.AutoField(
                        db_column="subscription_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[
                            ("free", "Zdarma"),
                            ("monthly", "Měsíční"),
                            ("yearly", "Roční"),
                            ("lifetime", "Doživotní"),
                            ("trial", "Zkušební"),
                        ],
                        db_column="subscription_type",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(auto_now_add=True, db_column="start_date"),
                ),
                (
                    "end_date",
                    models.DateTimeField(blank=True, db_column="end_date", null=True),
                ),
                (
                    "trial_end_date",
                    models.DateTimeField(
                        blank=True, db_column="trial_end_date", null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_column="is_active", default=True)),
                (
                    "auto_renew",
                    models.BooleanField(db_column="auto_renew", default=True),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, db_column="payment_method", max_length=50, null=True
                    ),
                ),
                (
                    "external_subscription_id",
                    models.CharField(
                        blank=True,
                        db_column="external_subscription_id",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, db_column="notes", null=True)),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, db_column="cancelled_at", null=True
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True, db_column="cancellation_reason", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "module",
                    models.ForeignKey(
                        db_column="module_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_subscriptions",
                        to="fdk_cz.module",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_column="organization_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="module_subscriptions",
                        to="fdk_cz.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "FDK_user_module_subscription",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "payment_id",
                    models.AutoField(
                        db_column="payment_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_column="amount", decimal_places=2, max_digits=10
                    ),
                ),
                (
                    "currency",
                    models.CharField(db_column="currency", default="CZK", max_length=3),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Čeká na zpracování"),
                            ("completed", "Dokončeno"),
                            ("failed", "Selhalo"),
                            ("refunded", "Vráceno"),
                            ("cancelled", "Zrušeno"),
                        ],
                        db_column="status",
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(db_column="payment_method", max_length=50),
                ),
                (
                    "external_payment_id",
                    models.CharField(
                        blank=True,
                        db_column="external_payment_id",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, db_column="invoice_number", max_length=50, null=True
                    ),
                ),
                (
                    "invoice_url",
                    models.URLField(blank=True, db_column="invoice_url", null=True),
                ),
                (
                    "description",
                    models.TextField(blank=True, db_column="description", null=True),
                ),
                ("metadata", models.JSONField(db_column="metadata", default=dict)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, db_column="completed_at", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        db_column="subscription_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="fdk_cz.usermodulesubscription",
                    ),
                ),
            ],
            options={
                "db_table": "FDK_payment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModuleUsage",
            fields=[
                (
                    "usage_id",
                    models.AutoField(
                        db_column="usage_id", primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(db_column="action", max_length=100)),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, db_column="timestamp"),
                ),
                (
                    "details",
                    models.JSONField(blank=True, db_column="details", null=True),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, db_column="ip_address", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, db_column="user_agent", max_length=255, null=True
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        db_column="module_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="fdk_cz.module",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "FDK_module_usage",
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="FDK_module__user_id_9423b8_idx",
                    ),
                    models.Index(
                        fields=["module", "timestamp"],
                        name="FDK_module__module__ce81da_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="usermodulesubscription",
            index=models.Index(
                fields=["user", "is_active"], name="FDK_user_mo_user_id_26102e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usermodulesubscription",
            index=models.Index(
                fields=["end_date"], name="FDK_user_mo_end_dat_d6ba62_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usermodulesubscription",
            unique_together={("user", "module")},
        ),
    ]
