# Generated by Django 5.1.1 on 2025-11-01 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fdk_cz", "0034_module_modulebundle_usermodulesubscription_payment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GrantDocumentTemplate",
            fields=[
                (
                    "template_id",
                    models.AutoField(
                        db_column="template_id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, db_column="description", null=True),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("project_description", "Popis projektu"),
                            ("budget", "Rozpočet"),
                            ("timeline", "Časový harmonogram"),
                            ("team", "Složení týmu"),
                            ("motivation", "Motivační dopis"),
                            ("references", "Reference"),
                            ("other", "Jiné"),
                        ],
                        db_column="document_type",
                        max_length=100,
                    ),
                ),
                (
                    "fields_schema",
                    models.JSONField(
                        db_column="fields_schema",
                        default=list,
                        help_text='JSON pole objektů: [{"name": "field_name", "type": "text", "label": "Label", "required": true}]',
                    ),
                ),
                (
                    "template_content",
                    models.TextField(
                        db_column="template_content",
                        help_text="Markdown šablona s {{placeholders}}",
                    ),
                ),
                ("is_active", models.BooleanField(db_column="is_active", default=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
            ],
            options={
                "db_table": "FDK_grant_document_template",
            },
        ),
        migrations.CreateModel(
            name="GrantOpportunityBookmark",
            fields=[
                (
                    "bookmark_id",
                    models.AutoField(
                        db_column="bookmark_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        db_column="notes",
                        help_text="Osobní poznámky k příležitosti",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
            ],
            options={
                "db_table": "FDK_grant_opportunity_bookmark",
            },
        ),
        migrations.AddField(
            model_name="grantapplication",
            name="actual_received_amount",
            field=models.DecimalField(
                blank=True,
                db_column="actual_received_amount",
                decimal_places=2,
                help_text="Skutečně obdržená částka (může se lišit od schválené)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="grantapplication",
            name="completion_percentage",
            field=models.IntegerField(
                db_column="completion_percentage",
                default=0,
                help_text="Stupeň dokončení projektu (0-100%)",
            ),
        ),
        migrations.AddField(
            model_name="grantapplication",
            name="last_report_submitted",
            field=models.DateTimeField(
                blank=True, db_column="last_report_submitted", null=True
            ),
        ),
        migrations.AddField(
            model_name="grantapplication",
            name="lifecycle_stage",
            field=models.CharField(
                choices=[
                    ("preparation", "Příprava žádosti"),
                    ("submitted", "Odesláno"),
                    ("under_review", "Probíhá hodnocení"),
                    ("approved", "Schváleno"),
                    ("rejected", "Zamítnuto"),
                    ("in_progress", "V realizaci"),
                    ("reporting", "Reporting"),
                    ("completed", "Ukončeno"),
                    ("archived", "Archivováno"),
                ],
                db_column="lifecycle_stage",
                default="preparation",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="grantapplication",
            name="report_deadline",
            field=models.DateField(
                blank=True,
                db_column="report_deadline",
                help_text="Termín odevzdání závěrečné zprávy",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="grantcall",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_column="external_id",
                help_text="ID z externí databáze (dotaceEU, MŠMT)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="grantcall",
            name="external_metadata",
            field=models.JSONField(
                db_column="external_metadata",
                default=dict,
                help_text="Dodatečná data z externího API",
            ),
        ),
        migrations.AddField(
            model_name="grantcall",
            name="last_synced",
            field=models.DateTimeField(blank=True, db_column="last_synced", null=True),
        ),
        migrations.AddField(
            model_name="grantcall",
            name="max_amount",
            field=models.DecimalField(
                blank=True,
                db_column="max_amount",
                decimal_places=2,
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="grantcall",
            name="min_amount",
            field=models.DecimalField(
                blank=True,
                db_column="min_amount",
                decimal_places=2,
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="grantcall",
            name="priority",
            field=models.IntegerField(
                db_column="priority",
                default=0,
                help_text="Vyšší číslo = vyšší priorita zobrazení",
            ),
        ),
        migrations.AddField(
            model_name="grantcall",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manuální"),
                    ("dotaceeu", "DotaceEU"),
                    ("msmt", "MŠMT"),
                    ("other_api", "Jiné API"),
                ],
                db_column="source",
                default="manual",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="grantcall",
            name="source_url",
            field=models.URLField(
                blank=True,
                db_column="source_url",
                help_text="Odkaz na dotaci v původním systému",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="grantcall",
            name="tags",
            field=models.CharField(
                blank=True,
                db_column="tags",
                help_text="Tagy oddělené čárkami: startup,inovace,kultura",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="grantapplication",
            index=models.Index(
                fields=["lifecycle_stage", "-created_at"],
                name="FDK_grant_a_lifecyc_d2a595_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="grantapplication",
            index=models.Index(
                fields=["report_deadline"], name="FDK_grant_a_report__e2545a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grantcall",
            index=models.Index(
                fields=["external_id"], name="FDK_grant_c_externa_1f2780_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grantcall",
            index=models.Index(
                fields=["source", "is_active"], name="FDK_grant_c_source_6bc4f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grantcall",
            index=models.Index(
                fields=["-priority", "-published_at"],
                name="FDK_grant_c_priorit_89f8b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="grantcall",
            index=models.Index(
                fields=["status", "end_date"], name="FDK_grant_c_status_d5cb7c_idx"
            ),
        ),
        migrations.AddField(
            model_name="grantdocumenttemplate",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="grantopportunitybookmark",
            name="call",
            field=models.ForeignKey(
                db_column="call_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="fdk_cz.grantcall",
            ),
        ),
        migrations.AddField(
            model_name="grantopportunitybookmark",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grant_bookmarks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grantopportunitybookmark",
            unique_together={("user", "call")},
        ),
    ]
