# Generated by Django 5.1.1 on 2025-11-02 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fdk_cz", "0035_grantdocumenttemplate_grantopportunitybookmark_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "category_id",
                    models.AutoField(
                        db_column="category_id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, db_column="description", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_column="organization_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_categories",
                        to="fdk_cz.organization",
                    ),
                ),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_category_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_categories",
                        to="fdk_cz.assetcategory",
                    ),
                ),
            ],
            options={
                "db_table": "FDK_asset_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "asset_id",
                    models.AutoField(
                        db_column="asset_id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=255)),
                (
                    "asset_number",
                    models.CharField(
                        db_column="asset_number", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, db_column="description", null=True),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="location", max_length=255, null=True
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(blank=True, db_column="purchase_date", null=True),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        db_column="purchase_price",
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True,
                        db_column="current_value",
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(db_column="currency", default="CZK", max_length=3),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktivní"),
                            ("maintenance", "Údržba"),
                            ("stored", "Uskladněno"),
                            ("disposed", "Vyřazeno"),
                            ("sold", "Prodáno"),
                        ],
                        db_column="status",
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, db_column="notes", null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_column="organization_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="fdk_cz.organization",
                    ),
                ),
                (
                    "responsible_person",
                    models.ForeignKey(
                        blank=True,
                        db_column="responsible_person_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_column="category_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="fdk_cz.assetcategory",
                    ),
                ),
            ],
            options={
                "db_table": "FDK_asset",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="B2BCompany",
            fields=[
                (
                    "company_id",
                    models.AutoField(
                        db_column="company_id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=255)),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, db_column="legal_name", max_length=255, null=True
                    ),
                ),
                (
                    "company_id_number",
                    models.CharField(
                        blank=True,
                        db_column="company_id_number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, db_column="tax_id", max_length=50, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_column="email", max_length=254, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_column="phone", max_length=20, null=True
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, db_column="website", null=True),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, db_column="street", max_length=255, null=True
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, db_column="city", max_length=100, null=True
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, db_column="postal_code", max_length=20, null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        db_column="country", default="Česká republika", max_length=100
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("supplier", "Dodavatel"),
                            ("customer", "Zákazník"),
                            ("partner", "Partner"),
                            ("competitor", "Konkurent"),
                            ("other", "Jiné"),
                        ],
                        db_column="category",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, db_column="tags", max_length=500, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, db_column="notes", null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_b2b_companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_column="organization_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="b2b_companies",
                        to="fdk_cz.organization",
                    ),
                ),
            ],
            options={
                "db_table": "FDK_b2b_company",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="B2BContract",
            fields=[
                (
                    "contract_id",
                    models.AutoField(
                        db_column="contract_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        db_column="contract_number", max_length=100, unique=True
                    ),
                ),
                ("title", models.CharField(db_column="title", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, db_column="description", null=True),
                ),
                (
                    "contract_value",
                    models.DecimalField(
                        blank=True,
                        db_column="contract_value",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(db_column="currency", default="CZK", max_length=3),
                ),
                ("start_date", models.DateField(db_column="start_date")),
                (
                    "end_date",
                    models.DateField(blank=True, db_column="end_date", null=True),
                ),
                (
                    "signed_date",
                    models.DateField(blank=True, db_column="signed_date", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Koncept"),
                            ("negotiation", "V jednání"),
                            ("signed", "Podepsáno"),
                            ("active", "Aktivní"),
                            ("completed", "Dokončeno"),
                            ("terminated", "Ukončeno"),
                            ("cancelled", "Zrušeno"),
                        ],
                        db_column="status",
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "categories",
                    models.CharField(
                        blank=True, db_column="categories", max_length=500, null=True
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, db_column="keywords", max_length=500, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="fdk_cz.b2bcompany",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_b2b_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_column="organization_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="b2b_contracts",
                        to="fdk_cz.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_column="project_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="b2b_contracts",
                        to="fdk_cz.project",
                    ),
                ),
            ],
            options={
                "db_table": "FDK_b2b_contract",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="B2BDocument",
            fields=[
                (
                    "document_id",
                    models.AutoField(
                        db_column="document_id", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_column="title", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, db_column="description", null=True),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, db_column="file_path", max_length=500, null=True
                    ),
                ),
                (
                    "file_url",
                    models.URLField(blank=True, db_column="file_url", null=True),
                ),
                (
                    "file_size",
                    models.IntegerField(blank=True, db_column="file_size", null=True),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, db_column="mime_type", max_length=100, null=True
                    ),
                ),
                (
                    "document_type",
                    models.CharField(db_column="document_type", max_length=100),
                ),
                (
                    "categories",
                    models.CharField(
                        blank=True, db_column="categories", max_length=500, null=True
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, db_column="keywords", max_length=500, null=True
                    ),
                ),
                (
                    "version",
                    models.CharField(db_column="version", default="1.0", max_length=20),
                ),
                ("is_latest", models.BooleanField(db_column="is_latest", default=True)),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, db_column="uploaded_at"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_column="company_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="fdk_cz.b2bcompany",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        db_column="contract_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="fdk_cz.b2bcontract",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_column="organization_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="b2b_documents",
                        to="fdk_cz.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="uploaded_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_b2b_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "FDK_b2b_document",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "department_id",
                    models.AutoField(
                        db_column="department_id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, db_column="description", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        db_column="manager_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_column="organization_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="fdk_cz.organization",
                    ),
                ),
                (
                    "parent_department",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_department_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_departments",
                        to="fdk_cz.department",
                    ),
                ),
            ],
            options={
                "db_table": "FDK_department",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "employee_id",
                    models.AutoField(
                        db_column="employee_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "first_name",
                    models.CharField(db_column="first_name", max_length=100),
                ),
                ("last_name", models.CharField(db_column="last_name", max_length=100)),
                (
                    "personal_id_number",
                    models.CharField(
                        blank=True,
                        db_column="personal_id_number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_column="email", max_length=254, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_column="phone", max_length=20, null=True
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, db_column="position", max_length=255, null=True
                    ),
                ),
                (
                    "employee_number",
                    models.CharField(
                        blank=True,
                        db_column="employee_number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Plný úvazek"),
                            ("part_time", "Částečný úvazek"),
                            ("contract", "Smlouva"),
                            ("temporary", "Dočasný"),
                            ("intern", "Stážista"),
                        ],
                        db_column="employment_type",
                        max_length=20,
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(blank=True, db_column="hire_date", null=True),
                ),
                (
                    "termination_date",
                    models.DateField(
                        blank=True, db_column="termination_date", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktivní"),
                            ("on_leave", "Na dovolené"),
                            ("suspended", "Pozastaveno"),
                            ("terminated", "Ukončeno"),
                        ],
                        db_column="status",
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True,
                        db_column="salary",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(db_column="currency", default="CZK", max_length=3),
                ),
                ("notes", models.TextField(blank=True, db_column="notes", null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        db_column="department_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="fdk_cz.department",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_column="organization_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="fdk_cz.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "FDK_employee",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="ITAsset",
            fields=[
                (
                    "asset_id",
                    models.AutoField(
                        db_column="asset_id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=255)),
                (
                    "asset_tag",
                    models.CharField(
                        db_column="asset_tag", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, db_column="description", null=True),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("server", "Server"),
                            ("workstation", "Pracovní stanice"),
                            ("laptop", "Notebook"),
                            ("mobile", "Mobilní zařízení"),
                            ("network", "Síťové zařízení"),
                            ("storage", "Úložiště"),
                            ("printer", "Tiskárna"),
                            ("software", "Software"),
                            ("license", "Licence"),
                            ("other", "Jiné"),
                        ],
                        db_column="asset_type",
                        max_length=20,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, db_column="manufacturer", max_length=100, null=True
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, db_column="model", max_length=100, null=True
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, db_column="serial_number", max_length=100, null=True
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(blank=True, db_column="purchase_date", null=True),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        db_column="purchase_price",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "warranty_expiry",
                    models.DateField(
                        blank=True, db_column="warranty_expiry", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktivní"),
                            ("in_repair", "V opravě"),
                            ("stored", "Uskladněno"),
                            ("disposed", "Vyřazeno"),
                        ],
                        db_column="status",
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        db_column="assigned_to_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_it_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_column="organization_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="it_assets",
                        to="fdk_cz.organization",
                    ),
                ),
            ],
            options={
                "db_table": "FDK_it_asset",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ITIncident",
            fields=[
                (
                    "incident_id",
                    models.AutoField(
                        db_column="incident_id", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_column="title", max_length=255)),
                ("description", models.TextField(db_column="description")),
                (
                    "incident_number",
                    models.CharField(
                        db_column="incident_number", max_length=50, unique=True
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Nízká"),
                            ("medium", "Střední"),
                            ("high", "Vysoká"),
                            ("critical", "Kritická"),
                        ],
                        db_column="priority",
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nový"),
                            ("assigned", "Přiřazeno"),
                            ("in_progress", "Řešení"),
                            ("resolved", "Vyřešeno"),
                            ("closed", "Uzavřeno"),
                        ],
                        db_column="status",
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(auto_now_add=True, db_column="reported_at"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, db_column="resolved_at", null=True
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, db_column="closed_at", null=True),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True, db_column="resolution_notes", null=True
                    ),
                ),
                (
                    "affected_asset",
                    models.ForeignKey(
                        blank=True,
                        db_column="affected_asset_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="fdk_cz.itasset",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        db_column="assigned_to_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_column="organization_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="it_incidents",
                        to="fdk_cz.organization",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="reported_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "FDK_it_incident",
                "ordering": ["-reported_at"],
            },
        ),
        migrations.CreateModel(
            name="Risk",
            fields=[
                (
                    "risk_id",
                    models.AutoField(
                        db_column="risk_id", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_column="title", max_length=255)),
                ("description", models.TextField(db_column="description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Technické"),
                            ("financial", "Finanční"),
                            ("operational", "Provozní"),
                            ("strategic", "Strategické"),
                            ("legal", "Právní"),
                            ("security", "Bezpečnostní"),
                            ("other", "Jiné"),
                        ],
                        db_column="category",
                        max_length=20,
                    ),
                ),
                (
                    "probability",
                    models.IntegerField(
                        choices=[
                            (1, "Velmi nízká"),
                            (2, "Nízká"),
                            (3, "Střední"),
                            (4, "Vysoká"),
                            (5, "Velmi vysoká"),
                        ],
                        db_column="probability",
                        default=3,
                    ),
                ),
                (
                    "impact",
                    models.IntegerField(
                        choices=[
                            (1, "Zanedbatelný"),
                            (2, "Malý"),
                            (3, "Střední"),
                            (4, "Velký"),
                            (5, "Kritický"),
                        ],
                        db_column="impact",
                        default=3,
                    ),
                ),
                ("risk_score", models.IntegerField(db_column="risk_score", default=9)),
                (
                    "mitigation_strategy",
                    models.TextField(
                        blank=True, db_column="mitigation_strategy", null=True
                    ),
                ),
                (
                    "contingency_plan",
                    models.TextField(
                        blank=True, db_column="contingency_plan", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identified", "Identifikováno"),
                            ("assessed", "Vyhodnoceno"),
                            ("mitigated", "Zmírněno"),
                            ("accepted", "Akceptováno"),
                            ("closed", "Uzavřeno"),
                        ],
                        db_column="status",
                        default="identified",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_column="organization_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="fdk_cz.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_column="owner_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_column="project_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="fdk_cz.project",
                    ),
                ),
            ],
            options={
                "db_table": "FDK_risk",
                "ordering": ["-risk_score", "-created_at"],
            },
        ),
    ]
